unpackaged/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Creditscore__c</fullName>
        <label>Credit score</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/LoanApplication__c.object
<CustomObject>
    <description>To store loan application</description>
    <fields>
        <fullName>Customer__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Loan Applications</relationshipLabel>
        <relationshipName>LoanApplications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>FundReleasedDate__c</fullName>
        <label>Fund Released Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LoanAmount__c</fullName>
        <description>To store the requestedloanamount</description>
        <label>Loan Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>InReview</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Fund released</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tenure__c</fullName>
        <description>To store tenure</description>
        <label>Tenure</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Loan Application</label>
    <nameField>
        <displayFormat>Loan-{0000}</displayFormat>
        <label>Loan application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/PaymentDetail__c.object
<CustomObject>
    <description>To store payment details</description>
    <fields>
        <fullName>Amountpayed__c</fullName>
        <description>from payment integration</description>
        <label>Amount payed</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Duedate__c</fullName>
        <description>DueDate</description>
        <label>Due date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EMIAmount__c</fullName>
        <formula>InterestAmount__c  +  PrincipalAmount__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>EMI Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>InterestAmount__c</fullName>
        <label>Interest amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>LoanApplication__c</fullName>
        <description>To link to payment</description>
        <label>Loan Application</label>
        <referenceTo>LoanApplication__c</referenceTo>
        <relationshipLabel>Payment Details</relationshipLabel>
        <relationshipName>Payment_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PrincipalAmount__c</fullName>
        <description>To store principal amount</description>
        <label>Principal Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Payment Detail</label>
    <nameField>
        <displayFormat>Pay-{0000}</displayFormat>
        <label>Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/classes/CustomerView.cls
public with sharing class CustomerView {
    @AuraEnabled(cacheable=true)
    public static List<CustomerViewWrapper> getCustomerDetail(String accountId)
    {
        List<Id> accountIdList = accountId.split(',');
        System.debug(accountIdList);
        List<CustomerViewWrapper> wrapperList = new  List<CustomerViewWrapper>();
        try {
            List<Account> accountList = [SELECT Id,Name,AccountNumber,(SELECT Id,CaseNumber,Status,Owner.Name FROM Cases)  FROM Account Where Id In:accountIdList];
            Map<Id,List<LoanApplication__c>> accountLpMap = new Map<Id,List<LoanApplication__c>>();
            For(LoanApplication__c lp: [SELECT Id,Tenure__c,Name,Status__c,RecordType.Name,LoanAmount__c,FundReleasedDate__c,Customer__c,(SELECT Id,EMIAmount__c,Duedate__c,Amountpayed__c,InterestAmount__c,PrincipalAmount__c FROM Payment_Details__r) FROM LoanApplication__c Where Customer__c In:accountIdList])
            {
                if(!accountLpMap.containsKey(lp.Customer__c)){
                    accountLpMap.put(lp.Customer__c,new List<LoanApplication__c>());
                }
                accountLpMap.get(lp.Customer__c).add(lp);
            }
            
            
            
            For(Account accRec : accountList){
                CustomerViewWrapper wrapper = new  CustomerViewWrapper();
                CustomerViewWrapper.Accounts acc = new CustomerViewWrapper.Accounts();
                acc.name = accRec.Name;
                acc.id = accRec.Id;
                acc.cases = accRec.Cases.size()>0? accRec.Cases:new List<Case>();
                //acc.creditScore = accRec.creditScore__c;
                //acc.adharKYC = accRec.AdharKYC__c;
                acc.accNumber = accRec.AccountNumber;
                acc.caseHeader = accRec.Name+'\''+'s Cases';
                acc.loanHeader = accRec.Name+'\''+'s Loan applications';
                acc.paymentHeader = accRec.Name+'\''+'s Payment Details';
                List<CustomerViewWrapper.LoanApplication> loanAppLst = new List<CustomerViewWrapper.LoanApplication>();
                if(accountLpMap.containsKey(accRec.Id)){
                    For(LoanApplication__c lp: accountLpMap.get(accRec.Id)){
                        CustomerViewWrapper.LoanApplication loanApp = new CustomerViewWrapper.LoanApplication();
                        loanApp.name = lp.Name;
                        loanApp.recordTypeName = lp.RecordType.Name;
                        loanApp.tenure = lp.Tenure__c;
                        loanApp.status = lp.Status__c;
                        loanApp.loanAmount = lp.LoanAmount__c;
                        List<CustomerViewWrapper.PaymentDetails> payLst = new List<CustomerViewWrapper.PaymentDetails>(); 
                        For(PaymentDetail__c payDet: lp.Payment_Details__r){
                            CustomerViewWrapper.PaymentDetails pay = new CustomerViewWrapper.PaymentDetails();
                            pay.duedate = payDet.Duedate__c;
                            pay.eMIAmount = payDet.EMIAmount__c;
                            pay.amountpayed= payDet.Amountpayed__c;
                            pay.interestAmount= payDet.InterestAmount__c;
                            pay.principalAmount = payDet.PrincipalAmount__c;
                            pay.paystatus =  payDet.Amountpayed__c==null?'Not Paid':'Paid';
                            payLst.add(pay);
                        }
                        loanApp.payDetail=payLst;
                        loanAppLst.add(loanApp);
                        
                    }
                }
                acc.loanAppl=loanAppLst;
                wrapper.accounts = acc;
                wrapperList.add(wrapper);
            }
            System.debug(wrapperList);
            
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
        return wrapperList;
    }
}